[project]
name = "dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohammed Misran", email = "mohammed.misran38@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "app",
    "pillow>=12.1.1",
    "requests>=2.32.5",
    "streamlit>=1.54.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "app",
]

[tool.uv.sources]
app = { workspace = true, editable = true }
